### ISSUE TITLE
Coordinates (mm9) for prediction sites

### ISSUE THREAD

**Issue by wlwtan** [EpigenomeClock/MouseEpigeneticClock#10]
Hi,

I am wondering if you are kind enough to provide the coordinates of the CpG sites for mm9 assembly? 

Thank you.

Wil

**Comment by Bonder-MJ** [comment]
Dear Wil,

You can liftover the mm10 coordinates to mm9 using tools such as:
http://genome.ucsc.edu/cgi-bin/hgLiftOver
However, the mapping of reads on the genome is not exactly the same between genome builds and we haven't tested this so I can't guarantee it works. We did see some differences between using a decoy or not using a decoy in the alignment so I would advice to remap your data.

Marc

**Comment by wlwtan** [comment]
Hi Marc,

Thanks.
We were in fact using a custom panel region-based biS-seq based on mm9 genome. I tried to lift over but failed.
Essentially, the sequences that I have extracted should mapped to mm10 based on blat.
If you have the coordinate and can share that, it will be great. I believe lots of people (who might want to use your tool), will be grateful for that.

Wil

**Comment by Bonder-MJ** [comment]
Dear Wil,
If you do a custom panel and know the regions that your panel targets than I would recommend lifting over these regions directly.  Did you add a window around your sites that you try to lift over?
Also if you want to liftover the sites you can extract them from either the training matrix or reading in the PredictionPackage_20170215.Rdata and extra the direct sites from the beta matrix. Again this was never done and I would not recommend doing so. I would try to get the raw data and remap against MM10.

Regards,
Marc
